name: flutter_login
description: A simple flutter login using firebase.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ^2.19.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
